<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Elements_banner-image</name>
   <tag></tag>
   <elementGuidId>ba74d0e8-8bf4-4e8a-9761-436dfc2664de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.banner-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Selenium Online Training&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>994db856-e327-4f67-97cf-e7409115db1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner-image</value>
      <webElementGuid>a0a5e3ac-e7c2-4255-9b20-edc874f426b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/WB.svg</value>
      <webElementGuid>0ddff8a0-a423-4d83-af1a-8c3e1931f944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Selenium Online Training</value>
      <webElementGuid>548c11b8-3dcb-4a77-a1f7-f1787b09d4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-height&quot;]/div[@class=&quot;home-content&quot;]/div[@class=&quot;home-banner&quot;]/a[1]/img[@class=&quot;banner-image&quot;]</value>
      <webElementGuid>28405d95-5113-4918-b617-f37e4da6983f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/a/img</value>
      <webElementGuid>a6a1ffc3-345c-4e34-83a7-213c7488a9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Selenium Online Training']</value>
      <webElementGuid>2c556ac9-b6cf-45fb-a78b-9e7e59a06e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/img</value>
      <webElementGuid>f289f6a0-b0e6-4390-b505-4af2b617469d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/WB.svg' and @alt = 'Selenium Online Training']</value>
      <webElementGuid>c59b0cb8-20cd-4a8c-a99c-40fff106a715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
