<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_dateOfBirthInput</name>
   <tag></tag>
   <elementGuidId>51e16edb-1881-4d40-be5b-b54a5a275d32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateOfBirthInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateOfBirthInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dateOfBirthInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5554a3c4-fcf1-444e-af5e-8394256a84e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63d0d8ae-e1ba-4779-947d-66a071ae11f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateOfBirthInput</value>
      <webElementGuid>03d1a9ec-97e8-40db-a213-a0759f41c1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e9d56510-73ef-4a47-a115-df5486705ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>15 Mar 2025</value>
      <webElementGuid>e1cabeab-6337-4528-a342-259b74d3212d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateOfBirthInput&quot;)</value>
      <webElementGuid>5f11975e-080f-40da-b7fd-51425c8cb1de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateOfBirthInput']</value>
      <webElementGuid>9b004e47-cc6b-4689-bcc7-edd49709b652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateOfBirth']/div/div/input</value>
      <webElementGuid>3e6c6801-72a0-4ba7-9121-19ca27ef8207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>f0837b2d-0a01-48a9-9299-41d7af542284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dateOfBirthInput']</value>
      <webElementGuid>1dbeef5b-e24f-4c5c-8571-f70640539f2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
