<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Date_datePickerMonthYearInput</name>
   <tag></tag>
   <elementGuidId>7fe1a75c-a75b-4028-a2b9-b03a586e5a09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datePickerMonthYearInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePickerMonthYearInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#datePickerMonthYearInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>deee3334-c70c-4154-8e43-0c416d93be4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23893baa-1548-48f1-a7b9-a7ac3f3a2c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePickerMonthYearInput</value>
      <webElementGuid>c4947be6-f206-4413-bdb6-399c6f061ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>c7f68728-180d-4812-b8ff-61920a7ccc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>03/15/2025</value>
      <webElementGuid>ac338fcb-dfa0-4800-bf0f-f285a469e481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePickerMonthYearInput&quot;)</value>
      <webElementGuid>b29e1be0-1bfe-486d-8b6d-3ec707aad650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePickerMonthYearInput']</value>
      <webElementGuid>29553978-b6d9-42a8-afd6-fd2b35bfd441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datePickerMonthYear']/div/div/input</value>
      <webElementGuid>51f1cd0f-9e2d-44a5-82f7-3feda1b18ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2f7a92e9-c611-4275-9f4c-971157d45a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datePickerMonthYearInput']</value>
      <webElementGuid>9576fe50-4955-4cb2-8f76-d4bfb690891c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
