<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date And Time_dateAndTimePickerInput</name>
   <tag></tag>
   <elementGuidId>fec18a50-2819-4e56-b0ef-6fabd28e7943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateAndTimePickerInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateAndTimePickerInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dateAndTimePickerInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2773adf7-d0a7-4803-8628-132fa38ecfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd4ff2f2-8b64-4dec-bd5b-87324ad62694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateAndTimePickerInput</value>
      <webElementGuid>a14a586f-da89-4c4b-b542-cc0ca7a2aa86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>2035ee9d-945e-4ae4-8621-9c57abe3dff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>March 15, 2025 4:37 AM</value>
      <webElementGuid>90e0f4fc-e7cb-4900-8831-c470868b2bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateAndTimePickerInput&quot;)</value>
      <webElementGuid>495016bb-4855-4978-bf36-5c6f0cb410b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateAndTimePickerInput']</value>
      <webElementGuid>b0f54af3-5868-4121-9c2a-b66ad479a2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateAndTimePicker']/div/div/input</value>
      <webElementGuid>35480656-b464-415f-983a-91ce6956f5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>a39cc8f8-738b-4784-a928-5d4e3bc0c50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dateAndTimePickerInput']</value>
      <webElementGuid>446ffa72-45cb-4b93-82fc-71a9b0066f2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
