<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_March 1998_react-datepicker__month-rea_d49733</name>
   <tag></tag>
   <elementGuidId>f27dcc91-1e37-4bde-839f-140448baef38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.react-datepicker__month-read-view--down-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dateAndTimePicker']/div[2]/div[2]/div/div/div[2]/div/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dateAndTimePicker span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7dc7c646-e1f7-414d-ac58-25326cd0e9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker__month-read-view--down-arrow</value>
      <webElementGuid>37ed1d91-86a3-47af-be9b-b70cdb5fd448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateAndTimePicker&quot;)/div[@class=&quot;react-datepicker__tab-loop&quot;]/div[@class=&quot;react-datepicker-popper&quot;]/div[1]/div[@class=&quot;react-datepicker&quot;]/div[@class=&quot;react-datepicker__month-container&quot;]/div[@class=&quot;react-datepicker__header&quot;]/div[@class=&quot;react-datepicker__header__dropdown react-datepicker__header__dropdown--scroll&quot;]/div[@class=&quot;react-datepicker__month-dropdown-container react-datepicker__month-dropdown-container--scroll&quot;]/div[@class=&quot;react-datepicker__month-read-view&quot;]/span[@class=&quot;react-datepicker__month-read-view--down-arrow&quot;]</value>
      <webElementGuid>78107cfb-d954-4134-ac37-4c107232e1ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateAndTimePicker']/div[2]/div[2]/div/div/div[2]/div/div[2]/div/div/span</value>
      <webElementGuid>8ad1cee4-f7a6-4944-bb4a-b034c66b4687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>aeb947a8-a0ef-41d4-ae5e-0fffb88ecfd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
